services:
  db:
    image: postgres:16
    container_name: renderia-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: renderia
    ports:
      - "5433:5432"
    volumes:
      - renderia_db:/var/lib/postgresql/data

volumes:
  renderia_db:
